### ISSUE TITLE
API Data Export

### ISSUE THREAD

**Issue by sergejzr** [rspace-os/rspace-client-python#11]
**Bug report**
Hello,
I noted a small issue with the export method in the "download_export" of the Client.

In file "/rspace_client/client.py", line 624
"export=export_format" should be changed to "export_format=export_format"

Reproducability:
Just try to use the download_export method, it will complain:

#--
TypeError                                 Traceback (most recent call last)
<ipython-input-11-813b9f775ab9> in <module>
----> 1 client.download_export(export_format="xml", scope="user", file_path="./"+str(44)+".zip", uid=44, wait_between_requests=30)

~/git/rspace-client-python/examples/rspace_client/client.py in download_export(self, export_format, scope, file_path, uid, wait_between_requests)
    552         :return: file path to the downloaded export archive
    553         """
--> 554         format=export_format
    555         job_id = self.start_export(export_format=export_format, scope=scope, uid=uid)['id']
    556 

TypeError: start_export() got an unexpected keyword argument 'format'
#--

When I just replicate the method and perform the change mentioned above, everything works.

**Comment by richarda23** [comment]
Hi Sergej, thanks, we'll fix this. Just out of interest, are you using the client from `pip` or running from this source code?

**Comment by sergejzr** [comment]
Hi Richard,
it is from pip

RSpace API server version: 1.69.43

version('rspace_client')
'1.5.0'

Best regards
Sergej

**Comment by noreferences** [comment]
Fixed, @richarda23 please make a release for the fix to be accessible from PyPI.

**Comment by richarda23** [comment]
Thanks @noreferences . Sergej, there is a new release with this fixed on PyPi
`pip install rspace-client==1.6.0`
