### ISSUE TITLE
download export a group

### ISSUE THREAD

**Issue by danielvarela** [rspace-os/rspace-client-python#33]
Hi,

I am trying to export all the data that we have in the group at community.researchspace.com. I use the following function:

![Screenshot 2022-06-10 at 14 22 02](https://user-images.githubusercontent.com/209552/173063205-6e46cf61-157a-4720-a15f-44f877f82425.png)

where client is an ELNClient instance.

When I try to download a selection of items, it works perfectly. But when I try to download the entire group with that function, it raises an Interval Server Error (500) as follows:

![Screenshot 2022-06-10 at 14 23 59](https://user-images.githubusercontent.com/209552/173063530-47ed13be-2b88-4563-bf8d-179a4e3baf6a.png)

Would you have any recommendation for handling this problem? Am I using something wrong? Thanks for your help.

**Comment by richarda23** [comment]
Hi Daniel
  
  
    That's an internal problem with RSpace server I think, the API call looks fine.
  
  
    We'll have a look as what is going wrong.
  
  
   Best wishes 
  
  
    Richard
  
  
   
    On 10/06/2022 13:26 Daniel Varela ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Hi,
   I am trying to export all the data that we have in the group at community.researchspace.com. I use the following function:
   
   where client is an ELNClient instance.
   When I try to download a selection of items, it works perfectly. But when I try to download the entire group with that function, it raises an Interval Server Error (500) as follows:
   
   Would you have any recommendation for handling this problem? Am I using something wrong? Thanks for your help.

**Comment by richarda23** [comment]
Hi Daniel
  
  
   Hm, OK, that rules that idea out then.
  
  
   I just tried doing an export of your group through the UI and that worked OK, so it's  not a problem with any of the data itself. 
  
  
   Will keep digging....
  
  
   
  
  
   
    On 10/06/2022 15:43 Daniel Varela ***@***.***> wrote:
   
   
    
   
   
    
   
   
   I though that it could be a permission issue as well, but on the try that I've posted I am used the apiKey generated by the PI of the group. I am going to give a try again just in case I missed something. Let me know if you need some additional information.
   Thank you for your help.
   Best,Daniel

**Comment by richarda23** [comment]
Hi, the problem was a timeout on the server.
The export works by first of all validating that all the requested items can be exported. This is synchronous and for some reason takes a long time for your export (about 7 minutes, and the default Apache timeout is 5 minutes). Then the actual export process starts which is asynchronous. 
The archive is assembled on the server, then zipped. 
The python client calls every 30 seconds to see if the job is complete or not.

I increased the timeout to 15 minutes and the export worked OK from the Python client (using v.2.4.0). 
Let me know how you get on!

**Comment by danielvarela** [comment]
I have tried now again and it's working perfectly!

Thank you very much for your help!

**Comment by richarda23** [comment]
Great to hear!
